<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  
  <title>PHP 异常处理 | 博客</title>

  
  <meta name="author" content="403 Forbidden">
  

  
  <meta name="description" content="异常（Exception）用于在指定的错误发生时改变脚本的正常流程。
什么是异常？PHP 5 提供了一种新的面向对象的错误处理方法。异常处理用于在指定的错误（异常）情况发生时改变脚本的正常流程。这种情况称为异常。当异常被触发时，通常会发生：

当前代码状态被保存


代码执行被切换到预定义的异常处理">
  

  
  
  <meta name="keywords" content="">
  

  <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <meta property="og:title" content="PHP 异常处理"/>

  <meta property="og:site_name" content="博客"/>

  
  <meta property="og:image" content="/favicon.ico"/>
  

  <link href="/favicon.ico" rel="icon">
  <link rel="alternate" href="/atom.xml" title="博客" type="application/atom+xml">
  <link rel="stylesheet" href="/css/style.css" media="screen" type="text/css">
</head>


<body>
<div class="blog">
  <div class="content">

    <header>
  <div class="site-branding">
    <h1 class="site-title">
      <a href="/">博客</a>
    </h1>
    <p class="site-description"></p>
  </div>
  <nav class="site-navigation">
    <ul>
      
        <li><a href="/">主页</a></li>
      
        <li><a href="/archives">归档</a></li>
      
    </ul>
  </nav>
</header>

    <main class="site-main posts-loop">
    <article>

  
    
    <h3 class="article-title"><span>PHP 异常处理</span></h3>
    
  

  <div class="article-top-meta">
    <span class="posted-on">
      <a href="/2014/09/12/PHP 异常处理/" rel="bookmark">
        <time class="entry-date published" datetime="2014-09-11T22:41:31.000Z">
          2014-09-12
        </time>
      </a>
    </span>
  </div>


  

  <div class="article-content">
    <div class="entry">
      
        <p><strong>异常（Exception）用于在指定的错误发生时改变脚本的正常流程。</strong></p>
<h2 id="什么是异常？"><a href="#什么是异常？" class="headerlink" title="什么是异常？"></a>什么是异常？</h2><p>PHP 5 提供了一种新的面向对象的错误处理方法。<br>异常处理用于在指定的错误（异常）情况发生时改变脚本的正常流程。这种情况称为异常。<br>当异常被触发时，通常会发生：</p>
<ul>
<li>当前代码状态被保存</li>
</ul>
<ul>
<li>代码执行被切换到预定义的异常处理器函数</li>
</ul>
<ul>
<li>根据情况，处理器也许会从保存的代码状态重新开始执行代码，终止脚本执行，或从代码中另外的位置继续执行脚本</li>
</ul>
<p>我们将展示不同的错误处理方法：</p>
<ul>
<li>异常的基本使用</li>
</ul>
<ul>
<li>创建自定义的异常处理器</li>
</ul>
<ul>
<li>多个异常</li>
</ul>
<ul>
<li>重新抛出异常</li>
</ul>
<ul>
<li>设置顶层异常处理器</li>
</ul>
<h2 id="异常的基本使用"><a href="#异常的基本使用" class="headerlink" title="异常的基本使用"></a>异常的基本使用</h2><p>当异常被抛出时，其后的代码不会继续执行，PHP 会尝试查找匹配的 “catch” 代码块。<br>如果异常没有被捕获，而且又没用使用 set_exception_handler() 作相应的处理的话，那么将发生一个严重的错误（致命错误），并且输出 “Uncaught Exception” （未捕获异常）的错误消息。<br>让我们尝试抛出一个异常，同时不去捕获它：<br><figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;?php</span></span><br><span class="line"><span class="comment">//create function with an exception</span></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">checkNum</span><span class="params">($number)</span></span></span><br><span class="line"><span class="function"> </span>&#123;</span><br><span class="line"> <span class="keyword">if</span>($number&gt;<span class="number">1</span>)</span><br><span class="line">  &#123;</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>(<span class="string">"Value must be 1 or below"</span>);</span><br><span class="line">  &#125;</span><br><span class="line"> <span class="keyword">return</span> <span class="keyword">true</span>;</span><br><span class="line"> &#125;</span><br><span class="line"><span class="comment">//trigger exception</span></span><br><span class="line">checkNum(<span class="number">2</span>);</span><br><span class="line"><span class="meta">?&gt;</span></span><br></pre></td></tr></table></figure></p>
<p>上面的代码会获得类似这样的一个错误：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Fatal error: Uncaught exception &apos;Exception&apos; </span><br><span class="line">with message &apos;Value must be 1 or below&apos; in C:\webfolder\test.php:6 </span><br><span class="line">Stack trace: #0 C:\webfolder\test.php(12): </span><br><span class="line">checkNum(28) #1 &#123;main&#125; thrown in C:\webfolder\test.php on line 6</span><br></pre></td></tr></table></figure></p>
<h3 id="Try-throw-和-catch"><a href="#Try-throw-和-catch" class="headerlink" title="Try, throw 和 catch"></a>Try, throw 和 catch</h3><p>要避免上面例子出现的错误，我们需要创建适当的代码来处理异常。<br>正确的处理程序应当包括：</p>
<ol>
<li>Try - 使用异常的函数应该位于 “try” 代码块内。如果没有触发异常，则代码将照常继续执行。但是如果异常被触发，会抛出一个异常。</li>
</ol>
<ol start="2">
<li>Throw - 这里规定如何触发异常。每一个 “throw” 必须对应至少一个 “catch”</li>
</ol>
<ol start="3">
<li>Catch - “catch” 代码块会捕获异常，并创建一个包含异常信息的对象</li>
</ol>
<p>让我们触发一个异常：<br><figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;?php</span></span><br><span class="line"><span class="comment">//创建可抛出一个异常的函数</span></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">checkNum</span><span class="params">($number)</span></span></span><br><span class="line"><span class="function"> </span>&#123;</span><br><span class="line"> <span class="keyword">if</span>($number&gt;<span class="number">1</span>)</span><br><span class="line">  &#123;</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>(<span class="string">"Value must be 1 or below"</span>);</span><br><span class="line">  &#125;</span><br><span class="line"> <span class="keyword">return</span> <span class="keyword">true</span>;</span><br><span class="line"> &#125;</span><br><span class="line"><span class="comment">//在 "try" 代码块中触发异常</span></span><br><span class="line"><span class="keyword">try</span></span><br><span class="line"> &#123;</span><br><span class="line"> checkNum(<span class="number">2</span>);</span><br><span class="line"> <span class="comment">//If the exception is thrown, this text will not be shown</span></span><br><span class="line"> <span class="keyword">echo</span> <span class="string">'If you see this, the number is 1 or below'</span>;</span><br><span class="line"> &#125;</span><br><span class="line"><span class="comment">//捕获异常</span></span><br><span class="line"><span class="keyword">catch</span>(<span class="keyword">Exception</span> $e)</span><br><span class="line"> &#123;</span><br><span class="line"> <span class="keyword">echo</span> <span class="string">'Message: '</span> .$e-&gt;getMessage();</span><br><span class="line"> &#125;</span><br><span class="line"><span class="meta">?&gt;</span></span><br></pre></td></tr></table></figure></p>
<p>上面代码将获得类似这样一个错误：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Message: Value must be 1 or below</span><br></pre></td></tr></table></figure></p>
<h3 id="例子解释："><a href="#例子解释：" class="headerlink" title="例子解释："></a>例子解释：</h3><p>上面的代码抛出了一个异常，并捕获了它：</p>
<ol>
<li>创建 checkNum() 函数。它检测数字是否大于 1。如果是，则抛出一个异常。</li>
</ol>
<ol start="2">
<li>在 “try” 代码块中调用 checkNum() 函数。</li>
</ol>
<ol start="3">
<li>checkNum() 函数中的异常被抛出</li>
</ol>
<ol start="4">
<li>“catch” 代码块接收到该异常，并创建一个包含异常信息的对象 ($e)。</li>
</ol>
<ol start="5">
<li>通过从这个 exception 对象调用 $e-&gt;getMessage()，输出来自该异常的错误消息</li>
</ol>
<p>不过，为了遵循“每个 throw 必须对应一个 catch”的原则，可以设置一个顶层的异常处理器来处理漏掉的错误。</p>
<h2 id="创建一个自定义的-Exception-类"><a href="#创建一个自定义的-Exception-类" class="headerlink" title="创建一个自定义的 Exception 类"></a>创建一个自定义的 Exception 类</h2><p>创建自定义的异常处理程序非常简单。我们简单地创建了一个专门的类，当 PHP 中发生异常时，可调用其函数。该类必须是 exception 类的一个扩展。<br>这个自定义的 exception 类继承了 PHP 的 exception 类的所有属性，您可向其添加自定义的函数。<br>我们开始创建 exception 类：<br><figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;?php</span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">customException</span> <span class="keyword">extends</span> <span class="title">Exception</span></span></span><br><span class="line"><span class="class"> </span>&#123;</span><br><span class="line"> <span class="keyword">public</span> <span class="function"><span class="keyword">function</span> <span class="title">errorMessage</span><span class="params">()</span></span></span><br><span class="line"><span class="function">  </span>&#123;</span><br><span class="line">  <span class="comment">//error message</span></span><br><span class="line">  $errorMsg = <span class="string">'Error on line '</span>.<span class="keyword">$this</span>-&gt;getLine().<span class="string">' in '</span>.<span class="keyword">$this</span>-&gt;getFile()</span><br><span class="line">  .<span class="string">': &lt;b&gt;'</span>.<span class="keyword">$this</span>-&gt;getMessage().<span class="string">'&lt;/b&gt; is not a valid E-Mail address'</span>;</span><br><span class="line">  <span class="keyword">return</span> $errorMsg;</span><br><span class="line">  &#125;</span><br><span class="line"> &#125;</span><br><span class="line">$email = <span class="string">"someone@example...com"</span>;</span><br><span class="line"><span class="keyword">try</span></span><br><span class="line"> &#123;</span><br><span class="line"> <span class="comment">//check if </span></span><br><span class="line"> <span class="keyword">if</span>(filter_var($email, FILTER_VALIDATE_EMAIL) === <span class="keyword">FALSE</span>)</span><br><span class="line">  &#123;</span><br><span class="line">  <span class="comment">//throw exception if email is not valid</span></span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> customException($email);</span><br><span class="line">  &#125;</span><br><span class="line"> &#125;</span><br><span class="line"><span class="keyword">catch</span> (customException $e)</span><br><span class="line"> &#123;</span><br><span class="line"> <span class="comment">//display custom message</span></span><br><span class="line"> <span class="keyword">echo</span> $e-&gt;errorMessage();</span><br><span class="line"> &#125;</span><br><span class="line"><span class="meta">?&gt;</span></span><br></pre></td></tr></table></figure></p>
<p>这个新的类是旧的 exception 类的副本，外加 errorMessage() 函数。正因为它是旧类的副本，因此它从旧类继承了属性和方法，我们可以使用 exception 类的方法，比如 getLine() 、 getFile() 以及 getMessage()。</p>
<h3 id="例子解释：-1"><a href="#例子解释：-1" class="headerlink" title="例子解释："></a>例子解释：</h3><p>上面的代码抛出了一个异常，并通过一个自定义的 exception 类来捕获它：</p>
<ol>
<li>customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</li>
</ol>
<ol start="2">
<li>创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一条错误消息</li>
</ol>
<ol start="3">
<li>把 $email 变量设置为不合法的 e-mail 地址字符串</li>
</ol>
<ol start="4">
<li>执行 “try” 代码块，由于 e-mail 地址不合法，因此抛出一个异常</li>
</ol>
<ol start="5">
<li>“catch” 代码块捕获异常，并显示错误消息</li>
</ol>
<h2 id="多个异常"><a href="#多个异常" class="headerlink" title="多个异常"></a>多个异常</h2><p>可以为一段脚本使用多个异常，来检测多种情况。<br>可以使用多个 if..else 代码块，或一个 switch 代码块，或者嵌套多个异常。这些异常能够使用不同的 exception 类，并返回不同的错误消息：<br><figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;?php</span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">customException</span> <span class="keyword">extends</span> <span class="title">Exception</span></span></span><br><span class="line"><span class="class"></span>&#123;</span><br><span class="line"><span class="keyword">public</span> <span class="function"><span class="keyword">function</span> <span class="title">errorMessage</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line"><span class="comment">//error message</span></span><br><span class="line">$errorMsg = <span class="string">'Error on line '</span>.<span class="keyword">$this</span>-&gt;getLine().<span class="string">' in '</span>.<span class="keyword">$this</span>-&gt;getFile()</span><br><span class="line">.<span class="string">': &lt;b&gt;'</span>.<span class="keyword">$this</span>-&gt;getMessage().<span class="string">'&lt;/b&gt; is not a valid E-Mail address'</span>;</span><br><span class="line"><span class="keyword">return</span> $errorMsg;</span><br><span class="line">&#125;</span><br><span class="line">&#125;</span><br><span class="line">$email = <span class="string">"someone@example.com"</span>;</span><br><span class="line"><span class="keyword">try</span></span><br><span class="line"> &#123;</span><br><span class="line"> <span class="comment">//check if </span></span><br><span class="line"> <span class="keyword">if</span>(filter_var($email, FILTER_VALIDATE_EMAIL) === <span class="keyword">FALSE</span>)</span><br><span class="line">  &#123;</span><br><span class="line">  <span class="comment">//throw exception if email is not valid</span></span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> customException($email);</span><br><span class="line">  &#125;</span><br><span class="line"> <span class="comment">//check for "example" in mail address</span></span><br><span class="line"> <span class="keyword">if</span>(strpos($email, <span class="string">"example"</span>) !== <span class="keyword">FALSE</span>)</span><br><span class="line">  &#123;</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>(<span class="string">"$email is an example e-mail"</span>);</span><br><span class="line">  &#125;</span><br><span class="line"> &#125;</span><br><span class="line"><span class="keyword">catch</span> (customException $e)</span><br><span class="line"> &#123;</span><br><span class="line"> <span class="keyword">echo</span> $e-&gt;errorMessage();</span><br><span class="line"> &#125;</span><br><span class="line"><span class="keyword">catch</span>(<span class="keyword">Exception</span> $e)</span><br><span class="line"> &#123;</span><br><span class="line"> <span class="keyword">echo</span> $e-&gt;getMessage();</span><br><span class="line"> &#125;</span><br><span class="line"><span class="meta">?&gt;</span></span><br></pre></td></tr></table></figure></p>
<h3 id="例子解释：-2"><a href="#例子解释：-2" class="headerlink" title="例子解释："></a>例子解释：</h3><p>上面的代码测试了两种条件，如何任何条件不成立，则抛出一个异常：</p>
<ol>
<li>customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</li>
</ol>
<ol start="2">
<li>创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一个错误消息。</li>
</ol>
<ol start="3">
<li>执行 “try” 代码块，在第一个条件下，不会抛出异常。</li>
</ol>
<ol start="4">
<li>由于 e-mail 含有字符串 “example”，第二个条件会触发异常。</li>
</ol>
<ol start="5">
<li>“catch” 代码块会捕获异常，并显示恰当的错误消息</li>
</ol>
<p>如果没有捕获 customException，紧紧捕获了 base exception，则在那里处理异常。</p>
<h2 id="重新抛出异常"><a href="#重新抛出异常" class="headerlink" title="重新抛出异常"></a>重新抛出异常</h2><p>有时，当异常被抛出时，您也许希望以不同于标准的方式对它进行处理。可以在一个 “catch” 代码块中再次抛出异常。<br>脚本应该对用户隐藏系统错误。对程序员来说，系统错误也许很重要，但是用户对它们并不感兴趣。为了让用户更容易使用，您可以再次抛出带有对用户比较友好的消息的异常：<br><figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;?php</span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">customException</span> <span class="keyword">extends</span> <span class="title">Exception</span></span></span><br><span class="line"><span class="class"> </span>&#123;</span><br><span class="line"> <span class="keyword">public</span> <span class="function"><span class="keyword">function</span> <span class="title">errorMessage</span><span class="params">()</span></span></span><br><span class="line"><span class="function">  </span>&#123;</span><br><span class="line">  <span class="comment">//error message</span></span><br><span class="line">  $errorMsg = <span class="keyword">$this</span>-&gt;getMessage().<span class="string">' is not a valid E-Mail address.'</span>;</span><br><span class="line">  <span class="keyword">return</span> $errorMsg;</span><br><span class="line">  &#125;</span><br><span class="line"> &#125;</span><br><span class="line">$email = <span class="string">"someone@example.com"</span>;</span><br><span class="line"><span class="keyword">try</span></span><br><span class="line"> &#123;</span><br><span class="line"> <span class="keyword">try</span></span><br><span class="line">  &#123;</span><br><span class="line">  <span class="comment">//check for "example" in mail address</span></span><br><span class="line">  <span class="keyword">if</span>(strpos($email, <span class="string">"example"</span>) !== <span class="keyword">FALSE</span>)</span><br><span class="line">   &#123;</span><br><span class="line">   <span class="comment">//throw exception if email is not valid</span></span><br><span class="line">   <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>($email);</span><br><span class="line">   &#125;</span><br><span class="line">  &#125;</span><br><span class="line"> <span class="keyword">catch</span>(<span class="keyword">Exception</span> $e)</span><br><span class="line">  &#123;</span><br><span class="line">  <span class="comment">//re-throw exception</span></span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> customException($email);</span><br><span class="line">  &#125;</span><br><span class="line"> &#125;</span><br><span class="line"><span class="keyword">catch</span> (customException $e)</span><br><span class="line"> &#123;</span><br><span class="line"> <span class="comment">//display custom message</span></span><br><span class="line"> <span class="keyword">echo</span> $e-&gt;errorMessage();</span><br><span class="line"> &#125;</span><br><span class="line"><span class="meta">?&gt;</span></span><br></pre></td></tr></table></figure></p>
<h3 id="例子解释：-3"><a href="#例子解释：-3" class="headerlink" title="例子解释："></a>例子解释：</h3><p>上面的代码检测在邮件地址中是否含有字符串 “example”。如果有，则再次抛出异常：</p>
<ol>
<li>customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</li>
</ol>
<ol start="2">
<li>创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一个错误消息。</li>
</ol>
<ol start="3">
<li>把 $email 变量设置为一个有效的邮件地址，但含有字符串 “example”。</li>
</ol>
<ol start="4">
<li>“try” 代码块包含另一个 “try” 代码块，这样就可以再次抛出异常。</li>
</ol>
<ol start="5">
<li>由于 e-mail 包含字符串 “example”，因此触发异常。</li>
</ol>
<ol start="6">
<li>“catch” 捕获到该异常，并重新抛出 “customException”。</li>
</ol>
<ol start="7">
<li>捕获到 “customException”，并显示一条错误消息。</li>
</ol>
<p>如果在其目前的 “try” 代码块中异常没有被捕获，则它将在更高层级上查找 catch 代码块。</p>
<h2 id="设置顶层异常处理器-（Top-Level-Exception-Handler）"><a href="#设置顶层异常处理器-（Top-Level-Exception-Handler）" class="headerlink" title="设置顶层异常处理器 （Top Level Exception Handler）"></a>设置顶层异常处理器 （Top Level Exception Handler）</h2><p>set_exception_handler() 函数可设置处理所有未捕获异常的用户定义函数。<br><figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&lt;?php</span></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">myException</span><span class="params">($exception)</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line"><span class="keyword">echo</span> <span class="string">"&lt;b&gt;Exception:&lt;/b&gt; "</span> , $exception-&gt;getMessage();</span><br><span class="line">&#125;</span><br><span class="line">set_exception_handler(<span class="string">'myException'</span>);</span><br><span class="line"><span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>(<span class="string">'Uncaught Exception occurred'</span>);</span><br><span class="line"><span class="meta">?&gt;</span></span><br></pre></td></tr></table></figure></p>
<p>以上代码的输出应该类似这样：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Exception: Uncaught Exception occurred</span><br></pre></td></tr></table></figure></p>
<p>在上面的代码中，不存在 “catch” 代码块，而是触发顶层的异常处理程序。应该使用此函数来捕获所有未被捕获的异常。</p>
<h2 id="异常的规则"><a href="#异常的规则" class="headerlink" title="异常的规则"></a>异常的规则</h2><ul>
<li>需要进行异常处理的代码应该放入 try 代码块内，以便捕获潜在的异常。</li>
</ul>
<ul>
<li>每个 try 或 throw 代码块必须至少拥有一个对应的 catch 代码块。</li>
</ul>
<ul>
<li>使用多个 catch 代码块可以捕获不同种类的异常。</li>
</ul>
<ul>
<li>可以在 try 代码块内的 catch 代码块中再次抛出（re-thrown）异常。</li>
</ul>
<p><strong>简而言之：如果抛出了异常，就必须捕获它。</strong></p>
<p>转载自 <a href="http://www.w3school.com.cn/php/php_exception.asp" target="_blank" rel="noopener">http://www.w3school.com.cn/php/php_exception.asp</a></p>

      
    </div>

  </div>

  <div class="article-footer">
    <div class="article-meta pull-left">

    
      

    <span class="post-categories">
      <i class="icon-categories"></i>
        <a href="/categories/Web-开发/">Web 开发</a>
    </span>
    

    

    </div>

    
  </div>
</article>

  

	<section id="comment" class="comment">
	  <div id="disqus_thread">
	  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	  </div>
	</section>

	<script type="text/javascript">
	var disqus_shortname = 'futa-ooo';
	(function(){
	  var dsq = document.createElement('script');
	  dsq.type = 'text/javascript';
	  dsq.async = true;
	  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
	  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	}());
	(function(){
	  var dsq = document.createElement('script');
	  dsq.type = 'text/javascript';
	  dsq.async = true;
	  dsq.src = '//' + disqus_shortname + '.disqus.com/count.js';
	  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	}());
	</script>




    </main>

    <footer class="site-footer">
  <p class="site-info">
    Proudly powered by <a href="https://hexo.io/" target="_blank">Hexo</a> and
    Theme by <a href="https://github.com/CodeDaraW/Hacker" target="_blank">Hacker</a>
    </br>
    
    &copy; 2018 403 Forbidden
    
  </p>
</footer>
    
  </div>
</div>
</body>
</html>