<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  
  <title>PHP 异常处理 | 博客</title>

  
  <meta name="author" content="403 Forbidden">
  

  
  <meta name="description" content="异常（Exception）用于在指定的错误发生时改变脚本的正常流程。
什么是异常？PHP 5 提供了一种新的面向对象的错误处理方法。异常处理用于在指定的错误（异常）情况发生时改变脚本的正常流程。这种情况称为异常。当异常被触发时，通常会发生：

当前代码状态被保存


代码执行被切换到预定义的异常处理">
  

  
  
  <meta name="keywords" content="">
  

  <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <meta property="og:title" content="PHP 异常处理"/>

  <meta property="og:site_name" content="博客"/>

  
  <meta property="og:image" content="/favicon.ico"/>
  

  <link href="/favicon.ico" rel="icon">
  <link rel="alternate" href="/atom.xml" title="博客" type="application/atom+xml">
  <link rel="stylesheet" href="/css/style.css" media="screen" type="text/css">
</head>


<body>
<div class="blog">
  <div class="content">

    <header>
  <div class="site-branding">
    <h1 class="site-title">
      <a href="/">博客</a>
    </h1>
    <p class="site-description"></p>
  </div>
  <nav class="site-navigation">
    <ul>
      
        <li><a href="/">主页</a></li>
      
        <li><a href="/archives">归档</a></li>
      
    </ul>
  </nav>
</header>

    <main class="site-main posts-loop">
    <article>

  
    
    <h3 class="article-title"><span>PHP 异常处理</span></h3>
    
  

  <div class="article-top-meta">
    <span class="posted-on">
      <a href="/2014/09/12/PHP 异常处理/" rel="bookmark">
        <time class="entry-date published" datetime="2014-09-11T22:41:31.000Z">
          2014-09-12
        </time>
      </a>
    </span>
  </div>


  

  <div class="article-content">
    <div class="entry">
      
        <p><strong>异常（Exception）用于在指定的错误发生时改变脚本的正常流程。</strong></p>
<h2 id="什么是异常？"><a href="#什么是异常？" class="headerlink" title="什么是异常？"></a>什么是异常？</h2><p>PHP 5 提供了一种新的面向对象的错误处理方法。<br>异常处理用于在指定的错误（异常）情况发生时改变脚本的正常流程。这种情况称为异常。<br>当异常被触发时，通常会发生：</p>
<ul>
<li>当前代码状态被保存</li>
</ul>
<ul>
<li>代码执行被切换到预定义的异常处理器函数</li>
</ul>
<ul>
<li>根据情况，处理器也许会从保存的代码状态重新开始执行代码，终止脚本执行，或从代码中另外的位置继续执行脚本</li>
</ul>
<p>我们将展示不同的错误处理方法：</p>
<ul>
<li>异常的基本使用</li>
</ul>
<ul>
<li>创建自定义的异常处理器</li>
</ul>
<ul>
<li>多个异常</li>
</ul>
<ul>
<li>重新抛出异常</li>
</ul>
<ul>
<li>设置顶层异常处理器</li>
</ul>
<h2 id="异常的基本使用"><a href="#异常的基本使用" class="headerlink" title="异常的基本使用"></a>异常的基本使用</h2><p>当异常被抛出时，其后的代码不会继续执行，PHP 会尝试查找匹配的 “catch” 代码块。<br>如果异常没有被捕获，而且又没用使用 set_exception_handler() 作相应的处理的话，那么将发生一个严重的错误（致命错误），并且输出 “Uncaught Exception” （未捕获异常）的错误消息。<br>让我们尝试抛出一个异常，同时不去捕获它：<br>`&lt;?php<br>//create function with an exception<br>function checkNum($number)<br> {<br> if($number&gt;1)<br>  {<br>  throw new Exception(“Value must be 1 or below”);<br>  }<br> return true;<br> }<br>//trigger exception<br>checkNum(2);<br>?&gt;<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line">上面的代码会获得类似这样的一个错误：</span><br><span class="line">`Fatal error: Uncaught exception &apos;Exception&apos; </span><br><span class="line">with message &apos;Value must be 1 or below&apos; in C:\webfolder\test.php:6 </span><br><span class="line">Stack trace: #0 C:\webfolder\test.php(12): </span><br><span class="line">checkNum(28) #1 &#123;main&#125; thrown in C:\webfolder\test.php on line 6</span><br></pre></td></tr></table></figure></p>
<h3 id="Try-throw-和-catch"><a href="#Try-throw-和-catch" class="headerlink" title="Try, throw 和 catch"></a>Try, throw 和 catch</h3><p>要避免上面例子出现的错误，我们需要创建适当的代码来处理异常。<br>正确的处理程序应当包括：</p>
<ol>
<li>Try - 使用异常的函数应该位于 “try” 代码块内。如果没有触发异常，则代码将照常继续执行。但是如果异常被触发，会抛出一个异常。</li>
</ol>
<ol start="2">
<li>Throw - 这里规定如何触发异常。每一个 “throw” 必须对应至少一个 “catch”</li>
</ol>
<ol start="3">
<li>Catch - “catch” 代码块会捕获异常，并创建一个包含异常信息的对象</li>
</ol>
<p>让我们触发一个异常：<br>`<br>&lt;?php<br>//创建可抛出一个异常的函数<br>function checkNum($number)<br> {<br> if($number&gt;1)<br>  {<br>  throw new Exception(“Value must be 1 or below”);<br>  }<br> return true;<br> }<br>//在 “try” 代码块中触发异常<br>try<br> {<br> checkNum(2);<br> //If the exception is thrown, this text will not be shown<br> echo ‘If you see this, the number is 1 or below’;<br> }<br>//捕获异常<br>catch(Exception $e)<br> {<br> echo ‘Message: ‘ .$e-&gt;getMessage();<br> }<br>?&gt;</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line">上面代码将获得类似这样一个错误：</span><br><span class="line">`Message: Value must be 1 or below</span><br></pre></td></tr></table></figure>
<h3 id="例子解释："><a href="#例子解释：" class="headerlink" title="例子解释："></a>例子解释：</h3><p>上面的代码抛出了一个异常，并捕获了它：</p>
<ol>
<li>创建 checkNum() 函数。它检测数字是否大于 1。如果是，则抛出一个异常。</li>
</ol>
<ol start="2">
<li>在 “try” 代码块中调用 checkNum() 函数。</li>
</ol>
<ol start="3">
<li>checkNum() 函数中的异常被抛出</li>
</ol>
<ol start="4">
<li>“catch” 代码块接收到该异常，并创建一个包含异常信息的对象 ($e)。</li>
</ol>
<ol start="5">
<li>通过从这个 exception 对象调用 $e-&gt;getMessage()，输出来自该异常的错误消息</li>
</ol>
<p>不过，为了遵循“每个 throw 必须对应一个 catch”的原则，可以设置一个顶层的异常处理器来处理漏掉的错误。</p>
<h2 id="创建一个自定义的-Exception-类"><a href="#创建一个自定义的-Exception-类" class="headerlink" title="创建一个自定义的 Exception 类"></a>创建一个自定义的 Exception 类</h2><p>创建自定义的异常处理程序非常简单。我们简单地创建了一个专门的类，当 PHP 中发生异常时，可调用其函数。该类必须是 exception 类的一个扩展。<br>这个自定义的 exception 类继承了 PHP 的 exception 类的所有属性，您可向其添加自定义的函数。<br>我们开始创建 exception 类：<br>`&lt;?php<br>class customException extends Exception<br> {<br> public function errorMessage()<br>  {<br>  //error message<br>  $errorMsg = ‘Error on line ‘.$this-&gt;getLine().’ in ‘.$this-&gt;getFile()<br>  .’: <b>‘.$this-&gt;getMessage().’</b> is not a valid E-Mail address’;<br>  return $errorMsg;<br>  }<br> }<br>$email = “someone@example…com”;<br>try<br> {<br> //check if<br> if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE)<br>  {<br>  //throw exception if email is not valid<br>  throw new customException($email);<br>  }<br> }<br>catch (customException $e)<br> {<br> //display custom message<br> echo $e-&gt;errorMessage();<br> }<br>?&gt;<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line">这个新的类是旧的 exception 类的副本，外加 errorMessage() 函数。正因为它是旧类的副本，因此它从旧类继承了属性和方法，我们可以使用 exception 类的方法，比如 getLine() 、 getFile() 以及 getMessage()。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">### 例子解释：</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">上面的代码抛出了一个异常，并通过一个自定义的 exception 类来捕获它：</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  1. customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  2. 创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一条错误消息</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  3. 把 $email 变量设置为不合法的 e-mail 地址字符串</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  4. 执行 &quot;try&quot; 代码块，由于 e-mail 地址不合法，因此抛出一个异常</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  5. &quot;catch&quot; 代码块捕获异常，并显示错误消息</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">h2&gt;多个异常</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">可以为一段脚本使用多个异常，来检测多种情况。</span><br><span class="line">可以使用多个 if..else 代码块，或一个 switch 代码块，或者嵌套多个异常。这些异常能够使用不同的 exception 类，并返回不同的错误消息：</span><br><span class="line">`&lt;?php</span><br><span class="line">class customException extends Exception</span><br><span class="line">&#123;</span><br><span class="line">public function errorMessage()</span><br><span class="line">&#123;</span><br><span class="line">//error message</span><br><span class="line">$errorMsg = &apos;Error on line &apos;.$this-&gt;getLine().&apos; in &apos;.$this-&gt;getFile()</span><br><span class="line">.&apos;: &lt;b&gt;&apos;.$this-&gt;getMessage().&apos;&lt;/b&gt; is not a valid E-Mail address&apos;;</span><br><span class="line">return $errorMsg;</span><br><span class="line">&#125;</span><br><span class="line">&#125;</span><br><span class="line">$email = &quot;someone@example.com&quot;;</span><br><span class="line">try</span><br><span class="line"> &#123;</span><br><span class="line"> //check if </span><br><span class="line"> if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE)</span><br><span class="line">  &#123;</span><br><span class="line">  //throw exception if email is not valid</span><br><span class="line">  throw new customException($email);</span><br><span class="line">  &#125;</span><br><span class="line"> //check for &quot;example&quot; in mail address</span><br><span class="line"> if(strpos($email, &quot;example&quot;) !== FALSE)</span><br><span class="line">  &#123;</span><br><span class="line">  throw new Exception(&quot;$email is an example e-mail&quot;);</span><br><span class="line">  &#125;</span><br><span class="line"> &#125;</span><br><span class="line">catch (customException $e)</span><br><span class="line"> &#123;</span><br><span class="line"> echo $e-&gt;errorMessage();</span><br><span class="line"> &#125;</span><br><span class="line">catch(Exception $e)</span><br><span class="line"> &#123;</span><br><span class="line"> echo $e-&gt;getMessage();</span><br><span class="line"> &#125;</span><br><span class="line">?&gt;</span><br></pre></td></tr></table></figure></p>
<h3 id="例子解释：-1"><a href="#例子解释：-1" class="headerlink" title="例子解释："></a>例子解释：</h3><p>上面的代码测试了两种条件，如何任何条件不成立，则抛出一个异常：</p>
<ol>
<li>customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</li>
</ol>
<ol start="2">
<li>创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一个错误消息。</li>
</ol>
<ol start="3">
<li>执行 “try” 代码块，在第一个条件下，不会抛出异常。</li>
</ol>
<ol start="4">
<li>由于 e-mail 含有字符串 “example”，第二个条件会触发异常。</li>
</ol>
<ol start="5">
<li>“catch” 代码块会捕获异常，并显示恰当的错误消息</li>
</ol>
<p>如果没有捕获 customException，紧紧捕获了 base exception，则在那里处理异常。</p>
<h2 id="重新抛出异常"><a href="#重新抛出异常" class="headerlink" title="重新抛出异常"></a>重新抛出异常</h2><p>有时，当异常被抛出时，您也许希望以不同于标准的方式对它进行处理。可以在一个 “catch” 代码块中再次抛出异常。<br>脚本应该对用户隐藏系统错误。对程序员来说，系统错误也许很重要，但是用户对它们并不感兴趣。为了让用户更容易使用，您可以再次抛出带有对用户比较友好的消息的异常：<br>`&lt;?php<br>class customException extends Exception<br> {<br> public function errorMessage()<br>  {<br>  //error message<br>  $errorMsg = $this-&gt;getMessage().’ is not a valid E-Mail address.’;<br>  return $errorMsg;<br>  }<br> }<br>$email = “<a href="mailto:someone@example.com" target="_blank" rel="noopener">someone@example.com</a>“;<br>try<br> {<br> try<br>  {<br>  //check for “example” in mail address<br>  if(strpos($email, “example”) !== FALSE)<br>   {<br>   //throw exception if email is not valid<br>   throw new Exception($email);<br>   }<br>  }<br> catch(Exception $e)<br>  {<br>  //re-throw exception<br>  throw new customException($email);<br>  }<br> }<br>catch (customException $e)<br> {<br> //display custom message<br> echo $e-&gt;errorMessage();<br> }<br>?&gt;</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">### 例子解释：</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">上面的代码检测在邮件地址中是否含有字符串 &quot;example&quot;。如果有，则再次抛出异常：</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  1. customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  2. 创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一个错误消息。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  3. 把 $email 变量设置为一个有效的邮件地址，但含有字符串 &quot;example&quot;。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  4. &quot;try&quot; 代码块包含另一个 &quot;try&quot; 代码块，这样就可以再次抛出异常。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  5. 由于 e-mail 包含字符串 &quot;example&quot;，因此触发异常。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  6. &quot;catch&quot; 捕获到该异常，并重新抛出 &quot;customException&quot;。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">  7. 捕获到 &quot;customException&quot;，并显示一条错误消息。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">如果在其目前的 &quot;try&quot; 代码块中异常没有被捕获，则它将在更高层级上查找 catch 代码块。</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"></span><br><span class="line">## 设置顶层异常处理器 （Top Level Exception Handler）</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">set_exception_handler() 函数可设置处理所有未捕获异常的用户定义函数。</span><br><span class="line">`&lt;?php</span><br><span class="line">function myException($exception)</span><br><span class="line">&#123;</span><br><span class="line">echo &quot;&lt;b&gt;Exception:&lt;/b&gt; &quot; , $exception-&gt;getMessage();</span><br><span class="line">&#125;</span><br><span class="line">set_exception_handler(&apos;myException&apos;);</span><br><span class="line">throw new Exception(&apos;Uncaught Exception occurred&apos;);</span><br><span class="line">?&gt;</span><br></pre></td></tr></table></figure>
<p>以上代码的输出应该类似这样：<br><code>Exception: Uncaught Exception occurred
``</code></p>
<p>在上面的代码中，不存在 “catch” 代码块，而是触发顶层的异常处理程序。应该使用此函数来捕获所有未被捕获的异常。</p>
<h2 id="异常的规则"><a href="#异常的规则" class="headerlink" title="异常的规则"></a>异常的规则</h2><ul>
<li>需要进行异常处理的代码应该放入 try 代码块内，以便捕获潜在的异常。</li>
</ul>
<ul>
<li>每个 try 或 throw 代码块必须至少拥有一个对应的 catch 代码块。</li>
</ul>
<ul>
<li>使用多个 catch 代码块可以捕获不同种类的异常。</li>
</ul>
<ul>
<li>可以在 try 代码块内的 catch 代码块中再次抛出（re-thrown）异常。</li>
</ul>
<p><strong>简而言之：如果抛出了异常，就必须捕获它。</strong></p>
<p>转载自 <a href="http://www.w3school.com.cn/php/php_exception.asp" target="_blank" rel="noopener">http://www.w3school.com.cn/php/php_exception.asp</a></p>

      
    </div>

  </div>

  <div class="article-footer">
    <div class="article-meta pull-left">

    
      

    <span class="post-categories">
      <i class="icon-categories"></i>
        <a href="/categories/Web-开发/">Web 开发</a>
    </span>
    

    

    </div>

    
  </div>
</article>


    </main>

    <footer class="site-footer">
  <p class="site-info">
    Proudly powered by <a href="https://hexo.io/" target="_blank">Hexo</a> and
    Theme by <a href="https://github.com/CodeDaraW/Hacker" target="_blank">Hacker</a>
    </br>
    
    &copy; 2018 403 Forbidden
    
  </p>
</footer>
    
  </div>
</div>
</body>
</html>